# Generated by Django 3.0.7 on 2020-06-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='user',
            new_name='user_followed',
        ),
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='follow_to', through='profiles.Relationship', to='profiles.Profile'),
        ),
    ]
