# Generated by Django 3.0.7 on 2020-06-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200623_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='follow_to', through='profiles.Relationship', to='profiles.Profile'),
        ),
    ]
