# Generated by Django 3.0.7 on 2020-06-23 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200623_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='user_followed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='profiles.Profile'),
        ),
    ]
