# Generated by Django 3.0.7 on 2020-06-28 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200624_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='followed_by',
            field=models.ForeignKey(db_column='followed_by', on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='user_followed',
            field=models.ForeignKey(db_column='user_followed', on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='profiles.Profile'),
        ),
    ]
