# Generated by Django 3.0.7 on 2020-07-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200628_2204'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.UniqueConstraint(fields=('user_followed', 'followed_by'), name='single follow'),
        ),
    ]
