# Generated by Django 3.0.7 on 2020-06-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dweetaddons',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
