# Generated by Django 3.0.7 on 2020-06-15 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dweetaddons_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dweetaddons',
            name='like',
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('dweet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Dweets')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('dweet_id', 'user_id')},
            },
        ),
    ]
