# Generated by Django 3.0.7 on 2020-06-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200615_0836'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DweetAddons',
            new_name='Comments',
        ),
    ]
