# Generated by Django 3.0.7 on 2020-06-15 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200615_0837'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
