# Generated by Django 3.0.7 on 2020-06-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200620_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
