# Generated by Django 3.0.7 on 2020-06-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_likes_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='follower_id',
        ),
        migrations.AddField(
            model_name='followers',
            name='followers',
            field=models.TextField(default='', verbose_name='Follower ids'),
        ),
    ]
