# Generated by Django 3.0.7 on 2020-06-22 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200622_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='user_id',
            new_name='follower_id',
        ),
    ]
