# Generated by Django 3.0.7 on 2020-06-22 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200622_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='follower_id',
            new_name='liked_by',
        ),
    ]
