# Generated by Django 3.0.7 on 2020-06-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200622_2346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
