# Generated by Django 3.0.7 on 2020-06-28 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_delete_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='dweet_id',
            field=models.ForeignKey(db_column='dweet_id', on_delete=django.db.models.deletion.CASCADE, to='api.Dweets'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dweets',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likes',
            name='dweet_id',
            field=models.ForeignKey(db_column='dweet_id', on_delete=django.db.models.deletion.CASCADE, to='api.Dweets'),
        ),
    ]
